swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Barbiere
  # put the contact info for your development or API team
  contact:
    email: leonardo.teti@marconicloud.it
        #stefano.cacchiarelli@marconicloud.it
        #denisconstantin.cioineag@marconicloud.it
    
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers

paths:
  /users.json:
    get:
      tags:
      - developers
      summary: list users
      operationId: listUsers
      description: |
        List all users
      produces:
      - application/json
      responses:
        200:
          description: list items correctly
        400:
          description: bad input parameter
  /events.json:
    get:
      tags:
      - events
      summary: list events
      operationId: listEvents
      description: |
        List all events
      produces:
      - application/json
      responses:
        200:
          description: list items correctly
          schema:
            $ref: '#/definitions/Event'
        400:
          description: bad input parameter
  /users.json/{id}:
    get:
      tags:
      - developers
      summary: detail of a single user
      operationId: userDetail
      description: |
        Detail of a single user
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        200:
          description: list items correctly
    
          schema:
            description: error
        400:
          description: bad input parameter
  /newUser.json/{id}:
    put:
      tags:
      - developers
      summary: create a new user
      operationId: newUser
      description: |
        Create a new user
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        200:
          description: list items correctly
        400:
          description: bad input parameter
definitions:
  Event:
    type: object
    required:
    - event_id 
    - name
    properties:
      user_id:
        type: integer
        example: 27
      manager:
        type: string
        example: Claudio
      cost:
        type: integer
        example:  24
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /IIS-Marconi-Civitave/2022-5binf-barby/1.0.0
schemes:
 - https
# Added by API Auto Mocking Plugin
basePath: /sparvasterino/Barbiere/1.0.0
